start_identifier: 'STX (start identifier)'
device_address: 'Device address (factory setting „00“) (NN)'
sensor_serial_number: 'Serial number (NNNN)'
software_version: 'Software-Version (N.NN)'
date_sensor: 'Date of the sensor (tt.mm.jj)'
time_sensor: 'Time of the sensor (on request) (hh:mm:ss)'
weather_code_synop_4677_5min: '5M SYNOP Tab.4677 (5 minutes mean value) (NN)'
weather_code_synop_4680_5min : '5M SYNOP Tab.4680 (5 minutes mean value) (NN)'
weather_code_metar_4678_5min : '5M METAR Tab.4678 (5 minutes mean value) (AAAAA)'
precipitation_rate_5min  : '5M Intensität [mm/h] (5 minutes mean value) (NNN.NNN)'
weather_code_synop_4677: '1M SYNOP Tab.4677 (1 minute value) (NN)'
weather_code_synop_4680: '1M SYNOP Tab.4680 (1 minute value) (NN)'
weather_code_metar_4678: '1M METAR Tab.4678 (1 minute value) (AAAAA)'
precipitation_rate: '1M Intensity [mm/h] total precipitation (1 minute value) (NNN.NNN)'
rainfall_rate: '1M Intensity [mm/h] liquid precipitation (1 minute value) (NNN.NNN)'
snowfall_rate: '1M Intensity [mm/h] solid precipitation (1 minute value) (NNN.NNN)'
precipitation_accumulated: 'Precipitation amount [mm] (Reset with command „RA“) (NNNN.NN)'
mor_visibility: '1M Visibility in precipitation [0...99999m] (1 minute value) (NNNNN)'
reflectivity: '1M Radar reflectivity [-9.9...99.9dBZ] (1 minute value) (NN.N)'
quality_index: '1M Measuring quality [0...100%] (1 minute value) (NNN)'
max_hail_diameter: '1M Maximum diameter hail [mm] (1 minute value) (N.N)'
laser_status: 'Status Laser (OK/on:0, off:1)'
static_signal: 'Static signal (OK:0, Error:1)'
laser_temperature_analog_status: 'Status Laser temperature (analogue) (OK:0, Error:1)'
laser_temperature_digital_status: 'Status Laser temperature (digital) (OK:0, Error:1)'
laser_current_analog_status: 'Status Laser current (analogue) (OK:0, Error:1)'
laser_current_digital_status: 'Status Laser current (digital) (OK:0, Error:1)'
sensor_voltage_supply_status: 'Status Sensor supply (OK:0, Error:1)'
current_heating_pane_transmitter_head_status: 'Status Current pane heating laser head (OK:0, warning:1)'
current_heating_pane_receiver_head_status: 'Status Current pane heating receiver head (OK:0, warning:1)'
temperature_sensor_status: 'Status Temperature sensor (OK:0, warning:1)'
current_heating_voltage_supply_status: 'Status Heating supply (OK:0, warning:1)'
current_heating_house_status: 'Status Current heating housing (OK:0, warning:1)'
current_heating_heads_status: 'Status Current heating heads (OK:0, warning:1)'
current_heating_carriers_status: 'Status Current heating carriers (OK:0, warning:1)'
control_output_laser_power_status: 'Status Control output laser power (OK:0, warning:1)'
reserve_status: 'Reserve Status (0)'
temperature_interior : 'Interior temperature [°C] (NNN)'
laser_temperature: 'Temperature of laser driver 0-80°C (NN)'
laser_current_average: 'Mean value laser current [1/100 mA] (NNNN)'
control_voltage: 'Control voltage [mV] (reference value: 4010±5) (NNNN)'
optical_control_voltage_output: 'Optical control output [mV] (2300 … 6500) (NNNN)'
sensor_voltage_supply : 'Voltage sensor supply [1/10V] (NNN)'
current_heating_pane_transmitter_head : 'Current pane heating laser head [mA] (NNN)'
current_heating_pane_receiver_head: 'Current pane heating receiver head [mA] (NNN)'
temperature_ambient: 'Ambient temperature [°C] (NNN.N)'
current_heating_voltage_supply: 'Voltage Heating supply [1/10 V] (only 5.4110.x1.xxx, otherwise “999”) (NNN)'
current_heating_house: 'Current heating housing [mA] (only 5.4110.x1.xxx, otherwise “9999”) (NNNN)'
current_heating_heads: 'Current heating heads [mA] (only 5.4110.x1.xxx, otherwise “9999”) (NNNN)'
current_heating_carriers: 'Current heating carriers [mA] (only 5.4110.x1.xxx, otherwise “9999”) (NNNN)'
number_particles: 'Number of all measured particles (NNNNN)'
number_particles_internal_data: '„00000.000“ (internal data)'
number_particles_min_speed: 'Number of particles < minimal speed (0.15m/s) (NNNNN)'
number_particles_min_speed_internal_data: '„00000.000“ (internal data)'
number_particles_max_speed: 'Number of particles > maximal speed (20m/s) (NNNNN)'
number_particles_max_speed_internal_data: '„00000.000“ (internal data)'
number_particles_min_diameter: 'Number of particles < minimal diameter (0.15mm) (NNNNN)'
number_particles_min_diameter_internal_data: '„00000.000“ (internal data)'
number_particles_no_hydrometeor: 'Number of particles no hydrometeor'
number_particles_no_hydrometeor_internal_data: 'Total volume (gross) of this class'
number_particles_unknown_classification: 'Number of particles with unknown classification'
number_particles_unknown_classification_internal_data: 'Total volume (gross) of this class'
number_particles_class_1: 'Number of particles class 1'
number_particles_class_1_internal_data: 'Total volume (gross) of class 1'
number_particles_class_2: 'Number of particles class 2'
number_particles_class_2_internal_data: 'Total volume (gross) of class 2'
number_particles_class_3: 'Number of particles class 3'
number_particles_class_3_internal_data: 'Total volume (gross) of class 3'
number_particles_class_4: 'Number of particles class 4'
number_particles_class_4_internal_data: 'Total volume (gross) of class 4'
number_particles_class_5: 'Number of particles class 5'
number_particles_class_5_internal_data: 'Total volume (gross) of class 5'
number_particles_class_6: 'Number of particles class 6'
number_particles_class_6_internal_data: 'Total volume (gross) of class 6'
number_particles_class_7: 'Number of particles class 7'
number_particles_class_7_internal_data: 'Total volume (gross) of class 7'
number_particles_class_8: 'Number of particles class 8'
number_particles_class_8_internal_data: 'Total volume (gross) of class 8'
number_particles_class_9: 'Number of particles class 9'
number_particles_class_9_internal_data: 'Total volume (gross) of class 9'
raw_drop_number: 'Precipitation spectrum'
# '521': air_temperature
# '522': relative_humidity
# '523': wind_speed
# '524': wind_direction