date: ''
time: ''
sensor_status: ''
interval: 's'
RI: 'mm/h'
RA: 'mm'
RAT: 'mm'
W: 'mm3/m3'
Wg: 'g/m3'
Z: 'mm6/m3'
ZdB: 'dB'
EK: 'J/m2'
EF: 'J/m2/h'
N0: '1/m3/mm'
slope: '1/mm'
Dmax: 'mm'
ND: '1/m3/mm'
raw_drop_number: ''
