'01': date
'02': time
'03': sensor_status
'04': interval
'05': n1
'06': n2
'07': n3
'08': n4
'09': n5
'10': n6
'11': n7
'12': n8
'13': n9
'14': n10
'15': n11
'16': n12
'17': n13
'18': n14
'19': n15
'20': n16
'21': n17
'22': n18
'23': n19
'24': n20
'25': RI
'26': RA
'27': RAT
'28': W
'29': Wg
'30': Z
'31': ZdB
'32': EK
'33': EF
'34': N0
'35': slope
'36': ND
'37': Dmax
