time: 'Measurement start time'
sensor_status: 'Sensor status'
interval: 'Time interval between measurement'

RI: 'Rain intensity (mm/h)'
RA: 'Rain amount (mm)'
RAT: 'Total rain amount since start of measurement (mm)'
W: 'Liquid Water Content'
Wg: 'Liquid Water Content'
Z: 'Radar Reflectivity Factor'
ZdB: 'Radar Reflectivity Factor'
EK: 'Kinetic Energy'
EF: 'Energy Flux'
N0: 'Number concentration'
slope: 'Slope'
Dmax: 'Max Drop diameter'
ND: 'Number drop density'
raw_drop_number: 'Drop counts per diameter'
