rainfall_rate_32bit: 'float32'
rainfall_accumulated_32bit: 'float32'
weather_code_synop_4680: 'uint32'
weather_code_synop_4677: 'uint32'
weather_code_metar_4678: 'object'
weather_code_nws: 'object'
reflectivity_32bit: 'float32'
mor_visibility: 'uint16'
sample_interval: 'uint16'
laser_amplitude: 'uint32'
number_particles: 'uint32'
sensor_temperature: 'int8'
sensor_serial_number: 'object'
firmware_iop: 'object'
firmware_dsp: 'object'
sensor_heating_current: 'float32'
sensor_battery_voltage: 'float32'
sensor_status: 'uint8'
start_time: 'object'
sensor_time: 'object'
sensor_date: 'object'
station_name: 'object'
station_number: 'object'
rainfall_amount_absolute_32bit: 'float32'
error_code: 'uint8'
rainfall_rate_16_bit: 'float32'
rainfall_rate_12bit: 'float32'
rainfall_accumulated_16bit: 'float32'
reflectivity_16bit: 'float32'
raw_drop_concentration: 'object'
raw_drop_average_velocity: 'object'
raw_drop_number: 'object'
