center:
  0: 0.359
  1: 0.455
  2: 0.551
  3: 0.656
  4: 0.771
  5: 0.913
  6: 1.116
  7: 1.331 
  8: 1.506
  9: 1.665
  10: 1.912
  11: 2.259
  12: 2.584
  13: 2.869
  14: 3.198
  15: 3.544
  16: 3.916
  17: 4.350
  18: 4.859
  19: 5.373

bounds:
  0:
  - 0.313
  - 0.405
  1:
  - 0.405
  - 0.505
  2:
  - 0.505
  - 0.596
  3:
  - 0.596
  - 0.715
  4:
  - 0.715
  - 0.827
  5:
  - 0.827
  - 0.999
  6:
  - 0.999
  - 1.232
  7:
  - 1.232
  - 1.429
  8:
  - 1.429
  - 1.582
  9:
  - 1.582
  - 1.748
  10:
  - 1.748
  - 2.077
  11:
  - 2.077
  - 2.441
  12:
  - 2.441
  - 2.727
  13:
  - 2.727
  - 3.011
  14:
  - 3.011
  - 3.385
  15:
  - 3.385
  - 3.704
  16:
  - 3.704
  - 4.127
  17:
  - 4.127
  - 4.573
  18:
  - 4.573
  - 5.145
  19:
  - 5.145
  - 5.6

width:
  0: 0.092
  1: 0.1
  2: 0.091
  3: 0.119
  4: 0.112
  5: 0.172
  6: 0.233
  7: 0.197
  8: 0.153
  9: 0.166
  10: 0.329
  11: 0.364
  12: 0.286
  13: 0.284
  14: 0.374
  15: 0.319
  16: 0.423
  17: 0.446
  18: 0.572
  19: 0.455
