'01': date
'02': time
'03': status
'04': interval
'05': n1
'06': n2
'07': n3
'08': n4
'09': n5
'10': n6
'11': n7
'12': n8
'13': n9
'14': n10
'15': n11
'16': n12
'17': n13
'18': n14
'19': n15
'20': n16
'21': n17
'22': n18
'23': n19
'24': n20
'25': RI
'26': RA
'27': RAT
