center:
  0: 0.025
  1: 0.05
  2: 0.076
  3: 0.103
  4: 0.131
  5: 0.159
  6: 0.187
  7: 0.217
  8: 0.247
  9: 0.278
  10: 0.31
  11: 0.342
  12: 0.375
  13: 0.409
  14: 0.444
  15: 0.48
  16: 0.517
  17: 0.554
  18: 0.593
  19: 0.633
  20: 0.673
  21: 0.714
  22: 0.757
  23: 0.801
  24: 0.845
  25: 0.891
  26: 0.938
  27: 0.986
  28: 1.035
  29: 1.086
  30: 1.137
  31: 1.19
  32: 1.245
  33: 1.3
  34: 1.357
  35: 1.416
  36: 1.476
  37: 1.537
  38: 1.6
  39: 1.664
  40: 1.731
  41: 1.798
  42: 1.868
  43: 1.939
  44: 2.012
  45: 2.086
  46: 2.163
  47: 2.241
  48: 2.322
  49: 2.404
  50: 2.488
  51: 2.575
  52: 2.664
  53: 2.754
  54: 2.848
  55: 2.943
  56: 3.041
  57: 3.141
  58: 3.244
  59: 3.349
  60: 3.457
  61: 3.567
  62: 3.68
  63: 3.797
  64: 3.915
  65: 4.037
  66: 4.162
  67: 4.29
  68: 4.421
  69: 4.556
  70: 4.694
  71: 4.835
  72: 4.98
  73: 5.128
  74: 5.28
  75: 5.436
  76: 5.595
  77: 5.759
  78: 5.926
  79: 6.098
  80: 6.274
  81: 6.454
  82: 6.639
  83: 6.829
  84: 7.023
  85: 7.222
  86: 7.426
  87: 7.635
  88: 7.849
  89: 8.068
  90: 8.293
  91: 8.523
  92: 8.76
  93: 9.002
  94: 9.25
  95: 9.504
  96: 9.764
  97: 10.031
  98: 10.305
  99: 10.585
  100: 10.872
  101: 11.167
  102: 11.468
  103: 11.778
  104: 12.095
  105: 12.419
  106: 12.752
  107: 13.093
  108: 13.442
  109: 13.801
  110: 14.168
  111: 14.544
  112: 14.929
  113: 15.324
  114: 15.729
  115: 16.144
  116: 16.569
  117: 17.005
  118: 17.451
  119: 17.909
  120: 18.378
  121: 18.858
  122: 19.351
  123: 19.855
  124: 20.372
  125: 20.902
  126: 21.446
  127: 22.002
bounds:
  0:
    - 0.0125
    - 0.0376
  1:
    - 0.0376
    - 0.0633
  2:
    - 0.0633
    - 0.0897
  3:
    - 0.0897
    - 0.1167
  4:
    - 0.1167
    - 0.1444
  5:
    - 0.1444
    - 0.1728
  6:
    - 0.1728
    - 0.2019
  7:
    - 0.2019
    - 0.2317
  8:
    - 0.2317
    - 0.2622
  9:
    - 0.2622
    - 0.2935
  10:
    - 0.2935
    - 0.3256
  11:
    - 0.3256
    - 0.3584
  12:
    - 0.3584
    - 0.3921
  13:
    - 0.3921
    - 0.4267
  14:
    - 0.4267
    - 0.462
  15:
    - 0.462
    - 0.4983
  16:
    - 0.4983
    - 0.5354
  17:
    - 0.5354
    - 0.5735
  18:
    - 0.5735
    - 0.6125
  19:
    - 0.6125
    - 0.6525
  20:
    - 0.6525
    - 0.6935
  21:
    - 0.6935
    - 0.7355
  22:
    - 0.7355
    - 0.7785
  23:
    - 0.7785
    - 0.8226
  24:
    - 0.8226
    - 0.8678
  25:
    - 0.8678
    - 0.9141
  26:
    - 0.9141
    - 0.9616
  27:
    - 0.9616
    - 1.0102
  28:
    - 1.0102
    - 1.0601
  29:
    - 1.0601
    - 1.1112
  30:
    - 1.1112
    - 1.1635
  31:
    - 1.1635
    - 1.2172
  32:
    - 1.2172
    - 1.2721
  33:
    - 1.2721
    - 1.3285
  34:
    - 1.3285
    - 1.3862
  35:
    - 1.3862
    - 1.4454
  36:
    - 1.4454
    - 1.506
  37:
    - 1.506
    - 1.5682
  38:
    - 1.5682
    - 1.6319
  39:
    - 1.6319
    - 1.6971
  40:
    - 1.6971
    - 1.764
  41:
    - 1.764
    - 1.8325
  42:
    - 1.8325
    - 1.9028
  43:
    - 1.9028
    - 1.9748
  44:
    - 1.9748
    - 2.0485
  45:
    - 2.0485
    - 2.1241
  46:
    - 2.1241
    - 2.2016
  47:
    - 2.2016
    - 2.281
  48:
    - 2.281
    - 2.3623
  49:
    - 2.3623
    - 2.4457
  50:
    - 2.4457
    - 2.5312
  51:
    - 2.5312
    - 2.6187
  52:
    - 2.6187
    - 2.7085
  53:
    - 2.7085
    - 2.8004
  54:
    - 2.8004
    - 2.8947
  55:
    - 2.8947
    - 2.9912
  56:
    - 2.9912
    - 3.0902
  57:
    - 3.0902
    - 3.1916
  58:
    - 3.1916
    - 3.2956
  59:
    - 3.2956
    - 3.4021
  60:
    - 3.4021
    - 3.5113
  61:
    - 3.5113
    - 3.6231
  62:
    - 3.6231
    - 3.7378
  63:
    - 3.7378
    - 3.8553
  64:
    - 3.8553
    - 3.9756
  65:
    - 3.9756
    - 4.099
  66:
    - 4.099
    - 4.2255
  67:
    - 4.2255
    - 4.3551
  68:
    - 4.3551
    - 4.4878
  69:
    - 4.4878
    - 4.6239
  70:
    - 4.6239
    - 4.7634
  71:
    - 4.7634
    - 4.9063
  72:
    - 4.9063
    - 5.0528
  73:
    - 5.0528
    - 5.2029
  74:
    - 5.2029
    - 5.3567
  75:
    - 5.3567
    - 5.5143
  76:
    - 5.5143
    - 5.6759
  77:
    - 5.6759
    - 5.8414
  78:
    - 5.8414
    - 6.0111
  79:
    - 6.0111
    - 6.1849
  80:
    - 6.1849
    - 6.3631
  81:
    - 6.3631
    - 6.5457
  82:
    - 6.5457
    - 6.7328
  83:
    - 6.7328
    - 6.9245
  84:
    - 6.9245
    - 7.1211
  85:
    - 7.1211
    - 7.3224
  86:
    - 7.3224
    - 7.5288
  87:
    - 7.5288
    - 7.7403
  88:
    - 7.7403
    - 7.9571
  89:
    - 7.9571
    - 8.1792
  90:
    - 8.1792
    - 8.4068
  91:
    - 8.4068
    - 8.6401
  92:
    - 8.6401
    - 8.8791
  93:
    - 8.8791
    - 9.1241
  94:
    - 9.1241
    - 9.3751
  95:
    - 9.3751
    - 9.6324
  96:
    - 9.6324
    - 9.8961
  97:
    - 9.8961
    - 10.1663
  98:
    - 10.1663
    - 10.4432
  99:
    - 10.4432
    - 10.727
  100:
    - 10.727
    - 11.0178
  101:
    - 11.0178
    - 11.3158
  102:
    - 11.3158
    - 11.6212
  103:
    - 11.6212
    - 11.9342
  104:
    - 11.9342
    - 12.2549
  105:
    - 12.2549
    - 12.5836
  106:
    - 12.5836
    - 12.9204
  107:
    - 12.9204
    - 13.2656
  108:
    - 13.2656
    - 13.6194
  109:
    - 13.6194
    - 13.9819
  110:
    - 13.9819
    - 14.3534
  111:
    - 14.3534
    - 14.7342
  112:
    - 14.7342
    - 15.1243
  113:
    - 15.1243
    - 15.5242
  114:
    - 15.5242
    - 15.934
  115:
    - 15.934
    - 16.3539
  116:
    - 16.3539
    - 16.7842
  117:
    - 16.7842
    - 17.2252
  118:
    - 17.2252
    - 17.6772
  119:
    - 17.6772
    - 18.1403
  120:
    - 18.1403
    - 18.615
  121:
    - 18.615
    - 19.1014
  122:
    - 19.1014
    - 19.5999
  123:
    - 19.5999
    - 20.1107
  124:
    - 20.1107
    - 20.6342
  125:
    - 20.6342
    - 21.1707
  126:
    - 21.1707
    - 21.7205
  127:
    - 21.7205
    - 22.2838
width:
  0: 0.025
  1: 0.026
  2: 0.026
  3: 0.027
  4: 0.028
  5: 0.028
  6: 0.029
  7: 0.03
  8: 0.03
  9: 0.031
  10: 0.032
  11: 0.033
  12: 0.034
  13: 0.035
  14: 0.035
  15: 0.036
  16: 0.037
  17: 0.038
  18: 0.039
  19: 0.04
  20: 0.041
  21: 0.042
  22: 0.043
  23: 0.044
  24: 0.045
  25: 0.046
  26: 0.047
  27: 0.049
  28: 0.05
  29: 0.051
  30: 0.052
  31: 0.054
  32: 0.055
  33: 0.056
  34: 0.058
  35: 0.059
  36: 0.061
  37: 0.062
  38: 0.064
  39: 0.065
  40: 0.067
  41: 0.0685
  42: 0.07
  43: 0.072
  44: 0.074
  45: 0.076
  46: 0.078
  47: 0.079
  48: 0.081
  49: 0.083
  50: 0.086
  51: 0.087
  52: 0.09
  53: 0.092
  54: 0.094
  55: 0.097
  56: 0.099
  57: 0.101
  58: 0.104
  59: 0.107
  60: 0.109
  61: 0.112
  62: 0.115
  63: 0.118
  64: 0.12
  65: 0.123
  66: 0.127
  67: 0.13
  68: 0.133
  69: 0.136
  70: 0.139
  71: 0.143
  72: 0.147
  73: 0.15
  74: 0.154
  75: 0.158
  76: 0.162
  77: 0.165
  78: 0.17
  79: 0.174
  80: 0.178
  81: 0.183
  82: 0.187
  83: 0.192
  84: 0.197
  85: 0.201
  86: 0.206
  87: 0.212
  88: 0.217
  89: 0.222
  90: 0.228
  91: 0.233
  92: 0.239
  93: 0.245
  94: 0.251
  95: 0.257
  96: 0.264
  97: 0.27
  98: 0.277
  99: 0.284
  100: 0.291
  101: 0.298
  102: 0.305
  103: 0.313
  104: 0.321
  105: 0.329
  106: 0.337
  107: 0.345
  108: 0.354
  109: 0.362
  110: 0.372
  111: 0.381
  112: 0.39
  113: 0.4
  114: 0.41
  115: 0.42
  116: 0.43
  117: 0.441
  118: 0.452
  119: 0.463
  120: 0.475
  121: 0.486
  122: 0.498
  123: 0.511
  124: 0.523
  125: 0.537
  126: 0.55
  127: 0.563
