reference_voltage: "float32"
precipitation_rate: "float32"
precip_flag: "float32"
relative_wind_speed: "float32"
relative_wind_direction: "float32"
weather_code_synop_4677: "float32"
raw_drop_number: "str"
air_temperature: "float32"
relative_humidity: "float32"
wind_speed: "float32"
wind_direction: "float32"
