precipitation_rate:
  description: Total precipitation intensity
  long_name: Total precipitation intensity
  units: mm/h
reference_voltage:
  description: Reference voltage
  long_name: Reference_voltage
  units: "V"
relative_wind_speed:
  description: Relative wind speed
  long_name: Relative wind speed
  units: "m s-1"
precip_flag:
  description: Precipitation classification
  long_name: Precipitation flag
  flag_meanings: "rain snow mixed_phase true_zero_value inoperative_instrument harbor_time_no_data"
  flag_values: "0 1 2 3 4 5"
  units: ""
raw_drop_number:
  description: Precipitation spectrum
  long_name: Precipitation spectrum
  units: ""
air_temperature:
  description: "Air temperature in degrees Celsius (C)"
  long_name: Air temperature
  units: "degC"
relative_humidity:
  description: "Relative humidity in percent (%)"
  long_name: Relative humidity
  units: "%"
wind_speed:
  description: "Wind speed in m/s"
  long_name: Wind speed
  units: "m/s"
wind_direction:
  description: "Wind direction in degrees (0-360)"
  long_name: Wind direction
  units: "degrees"
