precipitation_rate:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 43200
precip_flag:
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 43200
  _FillValue: 255
reference_voltage:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 43200
weather_code_synop_4677:
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
  _FillValue: 255
relative_wind_speed:
  dtype: uint16
  scale_factor: 0.1
  add_offset: -99.9
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  _FillValue: 65535
  chunksizes: 43200
relative_wind_direction:
  dtype: uint16
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  _FillValue: 65535
  chunksizes: 43200
raw_drop_number:
  dtype: uint16
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  _FillValue: 65535
  chunksizes:
    - 43200
    - 128
air_temperature:
  dtype: uint16
  scale_factor: 0.1
  add_offset: -99.9
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  _FillValue: 65535
  chunksizes: 43200
relative_humidity:
  dtype: uint16
  scale_factor: 0.01
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  _FillValue: 65535
  chunksizes: 43200
wind_speed:
  dtype: uint16
  scale_factor: 0.1
  add_offset: -99.9
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  _FillValue: 65535
  chunksizes: 43200
wind_direction:
  dtype: uint16
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  _FillValue: 65535
  chunksizes: 43200
