sample_interval:
  dtype: uint16
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  _FillValue: 65535
M1:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
M2:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
M3:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
M4:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
M5:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
M6:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
Nt:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
R:
  dtype: uint16
  scale_factor: 0.01
  _FillValue: 65535
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
Rm:
  dtype: uint16
  scale_factor: 0.01
  _FillValue: 65535
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
P:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
Z:
  dtype: uint16
  scale_factor: 0.01
  add_offset: -60
  _FillValue: 65535
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
W:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
Dm:
  dtype: uint16
  scale_factor: 0.001
  _FillValue: 65535
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
sigma_m:
  dtype: uint16
  scale_factor: 0.001
  _FillValue: 65535
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
Dmode:
  dtype: uint16
  scale_factor: 0.001
  _FillValue: 65535
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
Nw:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
D50:
  dtype: uint16
  scale_factor: 0.001
  _FillValue: 65535
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
D10:
  dtype: uint16
  scale_factor: 0.001
  _FillValue: 65535
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
D90:
  dtype: uint16
  scale_factor: 0.001
  _FillValue: 65535
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
drop_number:
  dtype: uint16
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  _FillValue: 65535
raw_drop_number:
  dtype: uint16
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  _FillValue: 65535
drop_counts:
  dtype: uint32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  _FillValue: 4294967295
N:
  dtype: uint32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  _FillValue: 4294967295
Nremoved:
  dtype: uint32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  _FillValue: 4294967295
Nbins:
  dtype: uint8
  _FillValue: 255
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
Nbins_missing:
  dtype: uint8
  _FillValue: 255
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
Nbins_missing_consecutive:
  dtype: uint8
  _FillValue: 255
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
Nbins_missing_fraction:
  dtype: uint8
  scale_factor: 0.01
  _FillValue: 255
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
Dmin:
  dtype: uint16
  scale_factor: 0.001
  _FillValue: 65535
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
Dmax:
  dtype: uint16
  scale_factor: 0.001
  _FillValue: 65535
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
drop_average_velocity:
  dtype: uint16
  scale_factor: 0.001
  _FillValue: 65535
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
fall_velocity:
  dtype: uint16
  scale_factor: 0.001
  _FillValue: 65535
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
drop_number_concentration:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
drop_volume:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
drop_total_volume:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
drop_relative_volume_ratio:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
KEmin:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
KEmax:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
TKE:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
KED:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
KEF:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
DBZH:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
DBZV:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
ZDR:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
RHOHV:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
DELTAHV:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
LDR:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
KDP:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
AH:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
AV:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
ADR:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
ADR:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
R2:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
MAE:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
MaxAE:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
RelMaxAE:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
PeakDiff:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
RelPeakDiff:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
DmodeDiff:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
NtDiff:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
KLDiv:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false

