name: disdrodb
channels:
  - conda-forge
dependencies:
  - click
  - pyyaml
  - tqdm
  - pooch
  - donfig
  - requests
  - trollsift
  - netcdf4
  - pyarrow
  - numpy
  - scipy
  - pandas
  - dask[distributed]
  - xarray
  - bottleneck
  - flox
  - tectonic
  - matplotlib-base
  - pycolorbar
  # Docs
  - jupyter
  - sphinx
  - sphinx-book-theme
  - nbsphinx
  # Testing
  - setuptools
  - pre_commit
  - coverage
  - pytest
  - pytest-cov
  - pytest-mock
  - requests-mock
  - pydantic
  - pip
