start_identifier:
  n_digits: 1
  n_characters: 1
  n_decimals: 0
  n_naturals: 1
  data_range:
    - 0
    - 9
  nan_flags: null
  field_number: "01"
device_address:
  n_digits: 2
  n_characters: 2
  n_decimals: 0
  n_naturals: 2
  data_range:
    - 0
    - 99
  nan_flags: null
  field_number: "02"
sensor_serial_number:
  n_digits: 4
  n_characters: 4
  n_decimals: 0
  n_naturals: 4
  data_range:
    - 0
    - 9999
  nan_flags: null
  field_number: "03"
software_version:
  n_digits: 3
  n_characters: 4
  n_decimals: 1
  n_naturals: 2
  data_range:
    - 0
    - 9.99
  nan_flags: null
  field_number: "04"
sensor_date:
  n_digits: 6
  n_characters: 8
  n_decimals: 6
  n_naturals: 0
  data_range: null
  nan_flags: null
  field_number: "05"
sensor_time:
  n_digits: 6
  n_characters: 8
  n_decimals: 6
  n_naturals: 0
  data_range: null
  nan_flags: null
  field_number: "06"
weather_code_synop_4677_5min:
  n_digits: 2
  n_characters: 2
  n_decimals: 0
  n_naturals: 2
  data_range:
    - -4
    - 90
  nan_flags: -1
  field_number: "07"
weather_code_synop_4680_5min:
  n_digits: 2
  n_characters: 2
  n_decimals: 0
  n_naturals: 2
  data_range:
    - -1
    - 89
  nan_flags: -1
  field_number: 08
weather_code_metar_4678_5min:
  n_digits: 0
  n_characters: 5
  n_decimals: 0
  n_naturals: 0
  data_range: null
  nan_flags: null
  field_number: 09
precipitation_rate_5min:
  n_digits: 6
  n_characters: 7
  n_decimals: 3
  n_naturals: 3
  data_range:
    - 0.0
    - 999.999
  nan_flags: null
  field_number: "10"
weather_code_synop_4677:
  n_digits: 0
  n_characters: 5
  n_decimals: 0
  n_naturals: 0
  data_range:
    - -4
    - 90
  nan_flags: -1
  field_number: "11"
weather_code_synop_4680:
  n_digits: 0
  n_characters: 5
  n_decimals: 0
  n_naturals: 0
  data_range:
    - -1
    - 89
  nan_flags: -1
  field_number: "12"
weather_code_metar_4678:
  n_digits: 0
  n_characters: 5
  n_decimals: 0
  n_naturals: 0
  data_range: null
  nan_flags: null
  field_number: "13"
precipitation_rate:
  n_digits: 6
  n_characters: 7
  n_decimals: 3
  n_naturals: 3
  data_range:
    - 0.0
    - 999.999
  nan_flags: null
  field_number: "14"
rainfall_rate:
  n_digits: 6
  n_characters: 7
  n_decimals: 3
  n_naturals: 3
  data_range:
    - 0.0
    - 999.999
  nan_flags: null
  field_number: "15"
snowfall_rate:
  n_digits: 6
  n_characters: 7
  n_decimals: 3
  n_naturals: 3
  data_range:
    - 0.0
    - 999.999
  nan_flags: null
  field_number: "16"
precipitation_accumulated:
  n_digits: 6
  n_characters: 7
  n_decimals: 4
  n_naturals: 2
  data_range:
    - 0.0
    - 9999.99
  nan_flags: null
  field_number: "17"
mor_visibility:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "18"
reflectivity:
  n_digits: 3
  n_characters: 4
  n_decimals: 2
  n_naturals: 1
  data_range:
    - -9.9
    - 99.9
  nan_flags: null
  field_number: "19"
quality_index:
  n_digits: 3
  n_characters: 3
  n_decimals: 3
  n_naturals: 0
  data_range:
    - 0
    - 100
  nan_flags: 999
  field_number: "20"
max_hail_diameter:
  n_digits: 2
  n_characters: 3
  n_decimals: 1
  n_naturals: 1
  data_range:
    - 0.0
    - 9.9
  nan_flags: null
  field_number: "21"
laser_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  valid_values:
    - 0
    - 1
  field_number: "22"
static_signal:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  field_number: "23"
laser_temperature_analog_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  valid_values:
    - 0
    - 1
  field_number: "24"
laser_temperature_digital_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  valid_values:
    - 0
    - 1
  field_number: "25"
laser_current_analog_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  valid_values:
    - 0
    - 1
  field_number: "26"
laser_current_digital_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  valid_values:
    - 0
    - 1
  field_number: "27"
sensor_voltage_supply_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  valid_values:
    - 0
    - 1
  field_number: "28"
current_heating_pane_transmitter_head_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  field_number: "29"
current_heating_pane_receiver_head_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  valid_values:
    - 0
    - 1
  field_number: "30"
temperature_sensor_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  valid_values:
    - 0
    - 1
  field_number: "31"
current_heating_voltage_supply_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  valid_values:
    - 0
    - 1
  field_number: "32"
current_heating_house_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  valid_values:
    - 0
    - 1
  field_number: "33"
current_heating_heads_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  valid_values:
    - 0
    - 1
  field_number: "34"
current_heating_carriers_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  valid_values:
    - 0
    - 1
  field_number: "35"
control_output_laser_power_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 1
  nan_flags: null
  valid_values:
    - 0
    - 1
  field_number: "36"
reserve_status:
  n_digits: 1
  n_characters: 1
  n_decimals: 1
  n_naturals: 0
  data_range:
    - 0
    - 0
  nan_flags: null
  valid_values:
    - 0
    - 1
  field_number: "37"
temperature_interior:
  n_digits: 3
  n_characters: 3
  n_decimals: 3
  n_naturals: 0
  data_range:
    - -30
    - 999
  nan_flags: null
  field_number: "38"
laser_temperature:
  n_digits: 2
  n_characters: 2
  n_decimals: 2
  n_naturals: 0
  data_range:
    - 0
    - 80
  nan_flags: null
  field_number: "39"
laser_current_average:
  n_digits: 4
  n_characters: 4
  n_decimals: 4
  n_naturals: 0
  data_range:
    - 0
    - 9999
  nan_flags: null
  field_number: "40"
control_voltage:
  n_digits: 4
  n_characters: 4
  n_decimals: 4
  n_naturals: 0
  data_range: null
  nan_flags: null
  field_number: "41"
optical_control_voltage_output:
  n_digits: 4
  n_characters: 4
  n_decimals: 4
  n_naturals: 0
  data_range:
    - 0
    - 9999
  nan_flags: null
  field_number: "42"
sensor_voltage_supply:
  n_digits: 3
  n_characters: 3
  n_decimals: 3
  n_naturals: 0
  data_range: null
  nan_flags: null
  field_number: "43"
current_heating_pane_transmitter_head:
  n_digits: 3
  n_characters: 3
  n_decimals: 3
  n_naturals: 0
  data_range: null
  nan_flags: null
  field_number: "44"
current_heating_pane_receiver_head:
  n_digits: 3
  n_characters: 3
  n_decimals: 3
  n_naturals: 0
  data_range: null
  nan_flags: null
  field_number: "45"
temperature_ambient:
  n_digits: 4
  n_characters: 5
  n_decimals: 3
  n_naturals: 1
  data_range:
    - -999.9
    - 99999.0
  nan_flags: null
  field_number: "46"
current_heating_voltage_supply:
  n_digits: 3
  n_characters: 3
  n_decimals: 3
  n_naturals: 0
  data_range: null
  nan_flags: null
  field_number: "47"
current_heating_house:
  n_digits: 4
  n_characters: 4
  n_decimals: 4
  n_naturals: 0
  data_range: null
  nan_flags: null
  field_number: "48"
current_heating_heads:
  n_digits: 4
  n_characters: 4
  n_decimals: 4
  n_naturals: 0
  data_range: null
  nan_flags: null
  field_number: "49"
current_heating_carriers:
  n_digits: 4
  n_characters: 4
  n_decimals: 4
  n_naturals: 0
  data_range: null
  nan_flags: null
  field_number: "50"
number_particles:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "51"
number_particles_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "52"
number_particles_min_speed:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "53"
number_particles_min_speed_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "54"
number_particles_max_speed:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "55"
number_particles_max_speed_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "56"
number_particles_min_diameter:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "57"
number_particles_min_diameter_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "58"
number_particles_no_hydrometeor:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "59"
number_particles_no_hydrometeor_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "60"
number_particles_unknown_classification:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "61"
number_particles_unknown_classification_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "62"
number_particles_class_1:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "63"
number_particles_class_1_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "64"
number_particles_class_2:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "65"
number_particles_class_2_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "66"
number_particles_class_3:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "67"
number_particles_class_3_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "68"
number_particles_class_4:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "69"
number_particles_class_4_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "70"
number_particles_class_5:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "71"
number_particles_class_5_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "72"
number_particles_class_6:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "73"
number_particles_class_6_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "74"
number_particles_class_7:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "75"
number_particles_class_7_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "76"
number_particles_class_8:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "77"
number_particles_class_8_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "78"
number_particles_class_9:
  n_digits: 5
  n_characters: 5
  n_decimals: 5
  n_naturals: 0
  data_range:
    - 0
    - 99999
  nan_flags: null
  field_number: "79"
number_particles_class_9_internal_data:
  n_digits: 8
  n_characters: 9
  n_decimals: 5
  n_naturals: 3
  data_range:
    - 0.0
    - 99999.999
  nan_flags: null
  field_number: "80"
raw_drop_number:
  n_digits: 1317
  n_characters: 1756
  n_decimals: 1317
  n_naturals: 0
  data_range: null
  nan_flags: null
  dimension_order:
    - diameter_bin_center
    - velocity_bin_center
  n_values: 440
  field_number: "81"
air_temperature:
  n_digits: 4
  n_characters: 5
  n_decimals: 1
  n_naturals: 2
  data_range:
    - -40
    - 70
  nan_flags: 99999
  field_number: "521"
relative_humidity:
  n_digits: 5
  n_characters: 5
  n_decimals: 0
  n_naturals: 5
  data_range:
    - 0
    - 99999
  nan_flags: 99999
  field_number: "522"
wind_speed:
  n_digits: 3
  n_characters: 4
  n_decimals: 1
  n_naturals: 2
  data_range:
    - 0
    - 60
  nan_flags: null
  field_number: "523"
wind_direction:
  n_digits: 3
  n_characters: 3
  n_decimals: 0
  n_naturals: 3
  data_range:
    - 0
    - 360
  nan_flags: 999
  field_number: "524"
