precipitation_rate:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
precipitation_accumulated:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
weather_code_synop_4680:
  dtype: uint8
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
  _FillValue: 255
weather_code_metar_4678:
  dtype: str
  zlib: false
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
past_weather1:
  dtype: str
  zlib: false
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
past_weather2:
  dtype: str
  zlib: false
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
mor_visibility_5min:
  dtype: uint16
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
  _FillValue: 65535
mor_visibility:
  dtype: uint16
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
  _FillValue: 65535
number_particles:
  dtype: uint16
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
  _FillValue: 4294967295
sensor_temperature:
  dtype: uint16
  scale_factor: 0.1
  add_offset: -60.0
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
  _FillValue: 65535
obstruction_status:
  dtype: str
  zlib: false
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
sensor_status:
  dtype: str
  zlib: false
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
ambient_light_sensor_signal_status:
  dtype: str
  zlib: false
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
total_extinction_coefficient:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
transmissometer_extinction_coefficient:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
back_scatter_extinction_coefficient:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
ambient_light_sensor_signal:
  dtype: float32
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  chunksizes: 5000
raw_drop_number:
  dtype: uint16
  zlib: true
  complevel: 3
  shuffle: true
  fletcher32: false
  contiguous: false
  _FillValue: 65535
  chunksizes:
    - 5000
    - 16
    - 21
