center:
  0: 0.1875
  1: 0.3125
  2: 0.4375
  3: 0.625
  4: 0.875
  5: 1.125
  6: 1.375
  7: 1.625
  8: 1.875
  9: 2.25
  10: 2.75
  11: 3.25
  12: 3.75
  13: 4.25
  14: 4.75
  15: 5.25
  16: 5.75
  17: 6.25
  18: 6.75
  19: 7.25
  20: 7.75
  21: 54
bounds:
  0:
  - 0.125
  - 0.25
  1:
  - 0.25
  - 0.375
  2:
  - 0.375
  - 0.5
  3:
  - 0.5
  - 0.75
  4:
  - 0.75
  - 1.0
  5:
  - 1.0
  - 1.25
  6:
  - 1.25
  - 1.5
  7:
  - 1.5
  - 1.75
  8:
  - 1.75
  - 2.0
  9:
  - 2.0
  - 2.5
  10:
  - 2.5
  - 3.0
  11:
  - 3.0
  - 3.5
  12:
  - 3.5
  - 4.0
  13:
  - 4.0
  - 4.5
  14:
  - 4.5
  - 5.0
  15:
  - 5.0
  - 5.5
  16:
  - 5.5
  - 6.0
  17:
  - 6.0
  - 6.5
  18:
  - 6.5
  - 7.0
  19:
  - 7.0
  - 7.5
  20:
   - 7.5
   - 8.0
  21:
  - 8.0
  - 100
width:
  0: 0.125
  1: 0.125
  2: 0.125
  3: 0.25
  4: 0.25
  5: 0.25
  6: 0.25
  7: 0.25
  8: 0.25
  9: 0.5
  10: 0.5
  11: 0.5
  12: 0.5
  13: 0.5
  14: 0.5
  15: 0.5
  16: 0.5
  17: 0.5
  18: 0.5
  19: 0.5
  20: 0.5
  21: 92 
