start_identifier: ''
device_address: ''
sensor_serial_number: ''
firmware_DSP: ''
date_sensor: ''
time_sensor: ''
synop_4677_5min_weather_code: ''
synop_4680_5min_weather_code: ''
metar_4678_5min_weather_code: ''
intensity_total_5min: ''
synop_4677_weather_code: ''
synop_4680_weather_code: ''
metar_4678_weather_code: ''
intensity_total: ''
intensity_liquid: ''
intensity_solid: ''
accum_precip: ''
maximum_visibility: ''
radar_reflectivity: ''
quality_measurement: ''
max_diameter_hail: ''
laser_status: ''
static_signal: ''
laser_temperature_analog_status: ''
laser_temperature_digital_status: ''
laser_current_analog_status: ''
laser_current_digital_status: ''
sensor_status: ''
pane_heating_laser_head_current: ''
pane_heating_receiver_head_current: ''
temperature_sensor_status: ''
status_heating: ''
heating_house_current_status: ''
heating_heads_current_status: ''
heating_carriers_current_status: ''
control_output_laser_power_status: ''
reserve_status: ''
interior_temperature: ''
laser_temperature: ''
mean_laser_current: ''
control_voltage: ''
optical_control_output: ''
voltage_sensor_supply: ''
ambient_temperature: ''
voltage_heating_supply: ''
heating_house_current: ''
heating_heads_current: ''
heating_carriers_current: ''
number_particles: ''
number_particles_internal_data: ''
number_particles_min_speed: ''
number_particles_min_speed_internal_data: ''
number_particles_max_speed: ''
number_particles_max_speed_internal_data: ''
number_particles_min_diameter: ''
number_particles_min_diameter_internal_data: ''
number_particles_no_hydrometeor: ''
number_particles_no_hydrometeor_internal_data: ''
number_particles_no_classification: ''
number_particles_no_classification_internal_data: ''
number_particles_class_1: ''
number_particles_class_1_internal_data: ''
number_particles_class_2: ''
number_particles_class_2_internal_data: ''
number_particles_class_3: ''
number_particles_class_3_internal_data: ''
number_particles_class_4: ''
number_particles_class_4_internal_data: ''
number_particles_class_5: ''
number_particles_class_5_internal_data: ''
number_particles_class_6: ''
number_particles_class_6_internal_data: ''
number_particles_class_7: ''
number_particles_class_7_internal_data: ''
number_particles_class_8: ''
number_particles_class_8_internal_data: ''
number_particles_class_9: ''
number_particles_class_9_internal_data: ''
precipitation_spectrum: ''
diameter_speed: ''
