start_identifier: 'Start identifier'
device_address: 'Device address'
sensor_serial_number: 'Serial number'
software_version: 'Software version'
date_sensor: 'Date of the sensor'
time_sensor: 'Time of the sensor'
weather_code_synop_4677_5min: '5 min SYNOP Tab.4677'
weather_code_synop_4680_5min : '5 min SYNOP Tab.4680'
weather_code_metar_4678_5min : '5 min METAR Tab.4678'
precipitation_rate_5min  : '5 min precipitation rate'
weather_code_synop_4677: 'SYNOP Tab.4677'
weather_code_synop_4680: 'SYNOP Tab.4680'
weather_code_metar_4678: 'METAR Tab.4678'
precipitation_rate: 'Total precipitation intensity'
rainfall_rate: 'Liquid precipitation intensity'
snowfall_rate: 'Solid precipitation intensity'
precipitation_accumulated: 'Precipitation amount'
mor_visibility: 'Visibility in precipitation'
reflectivity: 'Radar reflectivity'
quality_index: 'Quility index'
max_hail_diameter: 'Maximum diameter hail'
laser_status: 'Status laser'
static_signal: 'Static signal'
laser_temperature_analog_status: 'Status analogue laser temperature'
laser_temperature_digital_status: 'Status digital laser temperature'
laser_current_analog_status: 'Status analogue laser current'
laser_current_digital_status: 'Status digital laser current'
sensor_voltage_supply_status: 'Status sensor supply'
current_heating_pane_transmitter_head_status: 'Status current pane heating laser head'
current_heating_pane_receiver_head_status: 'Status current pane heating reciver head'
temperature_sensor_status: 'Status temperature sensor'
current_heating_voltage_supply_status: 'Status heating supply'
current_heating_house_status: 'Status current heating housing'
current_heating_heads_status: 'Status current heating heads'
current_heating_carriers_status: 'Status current heating carriers'
control_output_laser_power_status: 'Status control output laser'
reserve_status: 'Reserve status'
temperature_interior : 'Interior temperature'
laser_temperature: 'Temperature of laser driver'
laser_current_average: 'Mean value laser current'
control_voltage: 'Control voltage'
optical_control_voltage_output: 'Optical control output'
sensor_voltage_supply : 'Voltage sensor supply'
current_heating_pane_transmitter_head : 'Current pane heating laser head'
current_heating_pane_receiver_head: 'Current pane heating receiver head'
temperature_ambient: 'Ambient temperature'
current_heating_voltage_supply: 'Voltage heating supply'
current_heating_house: 'Current heating housing'
current_heating_heads: 'Current heating head'
current_heating_carriers: 'Current heating carriers'
number_particles: 'Number of all measured particles'
number_particles_internal_data: 'Number of all measured particles internal data'
number_particles_min_speed: 'Number of particles < minimal speed (0.15m/s)'
number_particles_min_speed_internal_data: 'Number of particles < minimal speed (0.15m/s) internal data'
number_particles_max_speed: 'Number of particles > maximal speed (20m/s)'
number_particles_max_speed_internal_data: 'Number of particles > maximal speed (20m/s) internal data'
number_particles_min_diameter: 'Number of particles < minimal diameter (0.15mm)'
number_particles_min_diameter_internal_data: 'Number of particles < minimal diameter (0.15mm) internal data'
number_particles_no_hydrometeor: 'Number of particles no hydrometeor'
number_particles_no_hydrometeor_internal_data: 'Total volume of this class'
number_particles_unknown_classification: 'Number of particles with unknown classification'
number_particles_unknown_classification_internal_data: 'Number of particles with unknown classification internal data'
number_particles_class_1: 'Number of particles class 1'
number_particles_class_1_internal_data: 'Total volume of class 1'
number_particles_class_2: 'Number of particles class 2'
number_particles_class_2_internal_data: 'Total volume of class 2'
number_particles_class_3: 'Number of particles class 3'
number_particles_class_3_internal_data: 'Total volume of class 3'
number_particles_class_4: 'Number of particles class 4'
number_particles_class_4_internal_data: 'Total volume of class 4'
number_particles_class_5: 'Number of particles class 5'
number_particles_class_5_internal_data: 'Total volume of class 5'
number_particles_class_6: 'Number of particles class 6'
number_particles_class_6_internal_data: 'Total volume of class 6'
number_particles_class_7: 'Number of particles class 7'
number_particles_class_7_internal_data: 'Total volume of class 7'
number_particles_class_8: 'Number of particles class 8'
number_particles_class_8_internal_data: 'Total volume of class 8'
number_particles_class_9: 'Number of particles class 9'
number_particles_class_9_internal_data: 'Total volume of class 9'
raw_drop_number: 'Precipitation spectrum'
# '521': air_temperature
# '522': relative_humidity
# '523': wind_speed
# '524': wind_direction