start_identifier: ''
device_address: ''
sensor_serial_number: ''
software_version: ''
date_sensor: ''
time_sensor: ''
weather_code_synop_4677_5min: ''
weather_code_synop_4680_5min : ''
weather_code_metar_4678_5min : ''
precipitation_rate_5min  : 'mm/h'
weather_code_synop_4677: ''
weather_code_synop_4680: ''
weather_code_metar_4678: ''
precipitation_rate: 'mm/h'
rainfall_rate: 'mm/h'
snowfall_rate: 'mm/h'
precipitation_accumulated: 'mm'
mor_visibility: ''
reflectivity: 'dbZ'
quality_index: '%'
max_hail_diameter: 'mm'
laser_status: ''
static_signal: ''
laser_temperature_analog_status: ''
laser_temperature_digital_status: ''
laser_current_analog_status: ''
laser_current_digital_status: ''
sensor_voltage_supply_status: ''
current_heating_pane_transmitter_head_status: ''
current_heating_pane_receiver_head_status: ''
temperature_sensor_status: ''
current_heating_voltage_supply_status: ''
current_heating_house_status: ''
current_heating_heads_status: ''
current_heating_carriers_status: ''
control_output_laser_power_status: ''
reserve_status: ''
temperature_interior : '°C'
laser_temperature: '°C'
laser_current_average: 'mA'
control_voltage: 'mV'
optical_control_voltage_output: 'mV'
sensor_voltage_supply : 'V'
current_heating_pane_transmitter_head: 'mA'
current_heating_pane_receiver_head: 'mA'
temperature_ambient: '°C'
current_heating_voltage_supply: 'V'
current_heating_house: 'mA'
current_heating_heads: 'mA'
current_heating_carriers: 'mA'
number_particles: ''
number_particles_internal_data: ''
number_particles_min_speed: ''
number_particles_min_speed_internal_data: ''
number_particles_max_speed: ''
number_particles_max_speed_internal_data: ''
number_particles_min_diameter: ''
number_particles_min_diameter_internal_data: ''
number_particles_no_hydrometeor: '' 
number_particles_no_hydrometeor_internal_data: ''
number_particles_unknown_classification: ''
number_particles_unknown_classification_internal_data: ''
number_particles_class_1: ''
number_particles_class_1_internal_data: ''
number_particles_class_2: ''
number_particles_class_2_internal_data: ''
number_particles_class_3: ''
number_particles_class_3_internal_data: ''
number_particles_class_4: ''
number_particles_class_4_internal_data: ''
number_particles_class_5: ''
number_particles_class_5_internal_data: ''
number_particles_class_6: ''
number_particles_class_6_internal_data: ''
number_particles_class_7: ''
number_particles_class_7_internal_data: ''
number_particles_class_8: ''
number_particles_class_8_internal_data: ''
number_particles_class_9: ''
number_particles_class_9_internal_data: ''
raw_drop_number: ''
# '521': air_temperature
# '522': relative_humidity
# '523': wind_speed
# '524': wind_direction