center:
  0: 0.062  # 0.0625 ? 
  1: 0.187
  2: 0.312
  3: 0.437
  4: 0.562
  5: 0.687
  6: 0.812
  7: 0.937
  8: 1.062
  9: 1.187   # 1.1875
  10: 1.375
  11: 1.625
  12: 1.875
  13: 2.125
  14: 2.375
  15: 2.75
  16: 3.25
  17: 3.75
  18: 4.25
  19: 4.75
  20: 5.5
  21: 6.5
  22: 7.5
  23: 8.5
  24: 9.5
  25: 11.0
  26: 13.0
  27: 15.0
  28: 17.0
  29: 19.0
  30: 21.5
  31: 24.5
bounds:
  0:
  - 0.0
  - 0.1245
  1:
  - 0.1245
  - 0.2495
  2:
  - 0.2495
  - 0.3745
  3:
  - 0.3745
  - 0.4995
  4:
  - 0.4995
  - 0.6245
  5:
  - 0.6245
  - 0.7495
  6:
  - 0.7495
  - 0.8745
  7:
  - 0.8745
  - 0.9995
  8:
  - 0.9995
  - 1.1245
  9:
  - 1.1245
  - 1.25
  10:
  - 1.25
  - 1.5
  11:
  - 1.5
  - 1.75
  12:
  - 1.75
  - 2.0
  13:
  - 2.0
  - 2.25
  14:
  - 2.25
  - 2.5
  15:
  - 2.5
  - 3.0
  16:
  - 3.0
  - 3.5
  17:
  - 3.5
  - 4.0
  18:
  - 4.0
  - 4.5
  19:
  - 4.5
  - 5.0
  20:
  - 5.0
  - 6.0
  21:
  - 6.0
  - 7.0
  22:
  - 7.0
  - 8.0
  23:
  - 8.0
  - 9.0
  24:
  - 9.0
  - 10.0
  25:
  - 10.0
  - 12.0
  26:
  - 12.0
  - 14.0
  27:
  - 14.0
  - 16.0
  28:
  - 16.0
  - 18.0
  29:
  - 18.0
  - 20.0
  30:
  - 20.0
  - 23.0
  31:
  - 23.0
  - 26.0
width:
  0: 0.125 # 0.1245 ?
  1: 0.125
  2: 0.125
  3: 0.125
  4: 0.125
  5: 0.125
  6: 0.125
  7: 0.125
  8: 0.125
  9: 0.125
  10: 0.25
  11: 0.25
  12: 0.25
  13: 0.25
  14: 0.25
  15: 0.5
  16: 0.5
  17: 0.5
  18: 0.5
  19: 0.5
  20: 1.0
  21: 1.0
  22: 1.0
  23: 1.0
  24: 1.0
  25: 2.0
  26: 2.0
  27: 2.0
  28: 2.0
  29: 2.0
  30: 3.0
  31: 3.0
